server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://database-1.c2vkve4qdbl6.ap-northeast-2.rds.amazonaws.com/jino?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: rla8623327


#  h2:
#    console:
#      enabled: true